import type { Metadata } from "next";
import {  Crimson_Text, Geist, Geist_Mono, Playfair, Playfair_Display } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header";
import AboutPreview from "../features/home/components/AboutPreview";
import Footer from "../components/layout/Footer";
// import Header from 

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair_Display",
  subsets: ["latin"],
});

const crimsonText = Crimson_Text({
  variable: "--font-crimson-text",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${playfairDisplay.variable} ${crimsonText.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header/>
        {children}
        <Footer/>
        
        
        </body>
    </html>
  );
}
